import { PrismaClient } from "@prisma/client";

const images = [
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMiHz8yt7Y2jcOai3MlxK0rkBphqVCuJIP4wsUS",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMiaRMhEFfte5i0YzkjKbQUPWdoh18fywrGLgxR",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMiYyTtlsr0REju3xSgCV54tihs2qvTXlOnyoMH",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMiTgQ670M7m2kfQrVCqMx14snIZXKu0EyPRi9N",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMi5X8PaV5NIYOMh9gTpzofiDmuKQwk6XlLt78q",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMiHc8PSoY2jcOai3MlxK0rkBphqVCuJIP4wsUS",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMiEnHotPa76aSqRNoGYCedgTlUzBc3wWvnyEJk",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMiWPH5AyCLN5pX8UgW6h41oEzsqkKBwlHCIDfd",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMihx00UrMQYQydTADZhsuRL1Pkqrc3aCigSOeM",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMiDMZUIf1JWvZrKB7TH6x2eiNsunLzlU81jCgh",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMi37nilaO29WiohuJkb537asxq41XvPCIAUSet",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMiHLqgOHY2jcOai3MlxK0rkBphqVCuJIP4wsUS",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMiywQea9WMz5obH6h02rEvYPpqdw84a1Vy9GLB",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMiDwgLwTJWvZrKB7TH6x2eiNsunLzlU81jCghw",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMisfzp3toExAnXlgh5E6YMdOba9R8TK4J3etNf",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMiZE3jgtutS0VsPX5346wDlCoxRUa18ivqELpT",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMinKELRz0JhRsVpxXy2dPAQku3lGv4EioTgMN6",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMiBhuwVgnswZ7Yzbg5NrujxS9TAo3apUDBHy1M",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMiuPETPVhtqy9QWNFPMhCdRzZGiYS52X4HkpEV",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMidx6XXzlHD4AJZM9rW1qTh3pgfFYdQkBnatcK",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMiuy38KKhtqy9QWNFPMhCdRzZGiYS52X4HkpEV",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMifrPPTVlHADuhN0gVCWnRb1yXGlQrmsHvick7",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMiFS0AXvxPNwcJnIB48VMb63rfiHjZUDequOds",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMiQs6gYTFEibjfrazVHmtOpTUC9Yxlh8uNAgkB",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMi0ptV6F2eSmdRqkVp7YhsP8QLHIGczFBN2Jvl",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMiAufjncE4VPl98d4JeULtEb53oKgkiauzGy0r",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMiaMc3hgfte5i0YzkjKbQUPWdoh18fywrGLgxR",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMi6KM70CS58alBi92GbrSK1v6AU4ZHQkpXhILq",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMiLQ0lOfAHhu50Ogt7I8eyFm9flv2TXaDkYW1M",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMiAbxwDc4VPl98d4JeULtEb53oKgkiauzGy0rO",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMiuNYdSEhtqy9QWNFPMhCdRzZGiYS52X4HkpEV",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMiJtHoopTifhwtMaW7SgXUnHCxZmNq1GdpPs29",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMiE5dxJCa76aSqRNoGYCedgTlUzBc3wWvnyEJk",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMiXjqWYG38Wlmkj79MUIAEvPHS6ZGRsyzVr5Yg",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMigl3V9qpR1zGUqnTLKo4puvOBwc2Ajh5Y98ed",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMi3YHpJaO29WiohuJkb537asxq41XvPCIAUSet",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMiPG8EF5pNtUJh23pZE4sFQvXAyaPDK8dioSwx",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMiE1GN9ba76aSqRNoGYCedgTlUzBc3wWvnyEJk",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMiZQQOEpwutS0VsPX5346wDlCoxRUa18ivqELp",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMinWSUFv0JhRsVpxXy2dPAQku3lGv4EioTgMN6",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMiJ9wvcdTifhwtMaW7SgXUnHCxZmNq1GdpPs29",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMivxwVt8DlLG3pnzer2vJ8HfTiw1MRmkcWSod6",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMi0Rc0v4eSmdRqkVp7YhsP8QLHIGczFBN2JvlZ",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMireN6vTKqGBKWCOpcmh1j2oAR5v3dNg6TLlUs",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMis3g3w3ExAnXlgh5E6YMdOba9R8TK4J3etNfo",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMiPtt6bRSpNtUJh23pZE4sFQvXAyaPDK8dioSw",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMi1Jybx7LsTeaNxFrzZnPVtYpmc9SU785BAuH0",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMi8oJXYmVb1aUKdx3fXsTHc2bCpqmGSyuoMVL6",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMinIjQdP0JhRsVpxXy2dPAQku3lGv4EioTgMN6",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMi1YmivRLsTeaNxFrzZnPVtYpmc9SU785BAuH0",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMiJVV2RkDTifhwtMaW7SgXUnHCxZmNq1GdpPs2",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMiHm0DZnY2jcOai3MlxK0rkBphqVCuJIP4wsUS",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMipZhxIDcoCvMiD7QznFkb23lYLsg1hayK5ueG",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMirmqbBsKqGBKWCOpcmh1j2oAR5v3dNg6TLlUs",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMihcIlAHQYQydTADZhsuRL1Pkqrc3aCigSOeMo",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMi2w3P9CvA0D1e54uzakdnNyog86S97jVZGtBp",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMiTWSEUAM7m2kfQrVCqMx14snIZXKu0EyPRi9N",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMiI2LIYWloLptRQPTFHZyie8Xq2uJ0BwWjKOEU",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMiQspMU9ZFEibjfrazVHmtOpTUC9Yxlh8uNAgk",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMiPorYUhpNtUJh23pZE4sFQvXAyaPDK8dioSwx",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMil2reWdGCuFs5Xp4iVJZNh2YPG6n1WRyfHaM0",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMijOJ9AarXbpN72LxUqAQEsami10YSr9dVWoKz",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMionJ5tqd9mlizeUbAVgv1RFpHh3wkOJscnQ82",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMiWzp3S4CLN5pX8UgW6h41oEzsqkKBwlHCIDfd",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMiXVxFRm38Wlmkj79MUIAEvPHS6ZGRsyzVr5Yg",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMiCgGBLW16yRidz1VPME4xQlqUtghTo2JYH8Ke",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMidU9diulHD4AJZM9rW1qTh3pgfFYdQkBnatcK",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMiyi9gvNWMz5obH6h02rEvYPpqdw84a1Vy9GLB",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMisnPvxyExAnXlgh5E6YMdOba9R8TK4J3etNfo",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMiAIMsWu4VPl98d4JeULtEb53oKgkiauzGy0rO",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMifgUu24HADuhN0gVCWnRb1yXGlQrmsHvick78",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMiCr3uQn6yRidz1VPME4xQlqUtghTo2JYH8KeW",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMigaaIfXR1zGUqnTLKo4puvOBwc2Ajh5Y98edm",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMiSBtYVwggrECi2h08RPoIlLBAHWQOaedY15mD",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMiP3nXkzpNtUJh23pZE4sFQvXAyaPDK8dioSwx",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMiAkxdGo4VPl98d4JeULtEb53oKgkiauzGy0rO",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMinc3tSw0JhRsVpxXy2dPAQku3lGv4EioTgMN6",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMiK2IgoeUjNcArbCHVqlR6STuLQFiBIg0zwa2X",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMigsIo5bR1zGUqnTLKo4puvOBwc2Ajh5Y98edm",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMiTNJqJxM7m2kfQrVCqMx14snIZXKu0EyPRi9N",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMiQsrmBXjFEibjfrazVHmtOpTUC9Yxlh8uNAgk",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMiZDnHyButS0VsPX5346wDlCoxRUa18ivqELpT",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMi52XVEcNIYOMh9gTpzofiDmuKQwk6XlLt78qe",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMi6llWQlS58alBi92GbrSK1v6AU4ZHQkpXhILq",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMiPiEt8FpNtUJh23pZE4sFQvXAyaPDK8dioSwx",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMiheU6ynQYQydTADZhsuRL1Pkqrc3aCigSOeMo",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMiA97Qmk4VPl98d4JeULtEb53oKgkiauzGy0rO",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMi6RXqCF8S58alBi92GbrSK1v6AU4ZHQkpXhIL",
  },
  {
    imageSmall:
      "https://utfs.io/f/pMhNI7coCvMiWSGhygqCLN5pX8UgW6h41oEzsqkKBwlHCIDf",
    imageMedium:
      "https://utfs.io/f/pMhNI7coCvMixaEOyjuslPEcJh6WD85Ctsd1oIqZQ0ew93yN",
  },
];

const db = new PrismaClient();

const load = async () => {
  try {
    await db.$executeRaw`TRUNCATE TABLE "image" RESTART IDENTITY CASCADE`;
    await db.images.createMany({
      data: images,
    });
  } catch (e) {
    console.error(e);
    process.exit(1);
  } finally {
    await db.$disconnect();
  }
};

load();
