import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import { SessionProvider } from "next-auth/react";

import { auth } from "@/auth";
import { Providers } from "./providers";
import "./globals.scss";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ToDo 2.0",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={rubik.className}>
        <SessionProvider session={session}>
          <Providers>{children}</Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
